---
sidebar: sidebar 
permalink: create-knowledgebase.html 
keywords: ai, chatbot, creating, knowledge base 
summary: AIインフラを導入し、FSx for ONTAPデータストアからナレッジベースに統合するデータソースを特定したら、Workload Factoryを使用してナレッジベースを構築できます。このステップの一部として、AIの特性を定義し、会話のきっかけを作ります。 
---
= ナレッジベースの作成
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
AIインフラを導入し、FSx for ONTAPデータストアからナレッジベースに統合するデータソースを特定したら、Workload Factoryを使用してナレッジベースを構築できます。このステップの一部として、AIの特性を定義し、会話のきっかけを作ります。

.タスクの内容
ナレッジベースには、_パブリックモード_と_エンタープライズモード_という2つのデータ統合モダリティがあります。

パブリックモード:: ナレッジベースは、組織のデータソースを統合しなくても使用できます。この場合、ナレッジベースに統合されたアプリケーションは、インターネット上で公開されている情報からのみ結果を提供します。これは_public mode_integrationと呼ばれます。
Enterpriseモード:: ほとんどの場合、組織のデータソースをナレッジベースに統合する必要があります。これは、エンタープライズからの知識を提供するため、_Enterprise mode_integrationと呼ばれます。
+
--
組織のデータソースには、個人識別情報（PII）が含まれている場合があります。この機密情報を保護するために、ナレッジベースの作成および構成時に_data guardrails_を有効にすることができます。BlueXP  分類を利用したデータガードレールは、PIIを識別してマスクし、アクセスできず、取り出すことができないようにします。

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXPの分類について説明します"^]です。


NOTE: データガードレールはいつでも有効または無効にできます。データガードレールを有効に切り替えると、Workload Factoryはナレッジベース全体をゼロからスキャンするため、コストがかかります。

--




== ナレッジベースの作成と設定

ナレッジベースは、ナレッジベースの作成に使用するBedrock AIモデルや埋め込み形式などの特性を定義します。

.手順
. Workload Factoryにログインします。
. [AI Workloads]タイルで、*[Deploy & manage]*を選択します。
. [ナレッジベース]タブで、*[ナレッジベースの追加]*を選択します。
. [ナレッジベースの定義]ページで、ナレッジベースの設定を行います。
+
.. *名前*:ナレッジベースに使用する名前を入力します。
.. *説明*:ナレッジベースの詳細な説明を入力します。
.. *埋め込みモデル*:埋め込みモデルは、データがナレッジベースのベクトル埋め込みに変換される方法を定義します。Workload Factoryは次のモデルをサポートします。
+
*** Titan埋め込みG1 -テキスト
*** Titan埋め込みテキストv2
*** Titan Multimodal Embedding G1
+
Amazon Bedrockから埋め込みモデルを有効にしておく必要があります。

+
https://aws.amazon.com/bedrock/titan/["Amazon Titanの詳細"^]



.. *チャットモデル*: Amazon Bedrockに統合されているクロードチャットモデルから選択します。Amazon Bedrockからチャットモデルを有効にしておく必要があります。
+
選択に役立つ利用可能なモデルの詳細については、以下を参照してください。 https://aws.amazon.com/bedrock/claude/["Amazon BedrockのAnthropic's Claude"^]

.. *データガードレール*:データガードレールを有効にするか無効にするかを選択します。link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP  分類を活用したデータガードレールの詳細"^]です。
+
データガードレールを有効にするには、次の前提条件を満たしている必要があります。

+
*** BlueXP  分類と通信するには、サービスアカウントが必要です。サービスアカウントを作成するには、BlueXP  テナンシーアカウントで_Organization admin_roleが必要です。組織管理者ロールを持つメンバーは、BlueXP  ですべてのアクションを実行できます。link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member["BlueXP  でメンバーにロールを追加する方法を確認する"^]
*** AIエンジンは、 link:https://console.bluexp.netapp.com/["BlueXPコンソール"^]
*** で説明されているように、次の手順を実行する必要がありlink:https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html#quick-start["BlueXPの分類に関するドキュメント"^]ます。
+
.... BlueXPコネクタの作成
.... 環境が前提条件を満たしていることを確認する
.... BlueXP分類を導入します




.. *会話の開始*：このナレッジベースを使用するチャットボットと対話するユーザーに表示される会話の開始プロンプトを最大4つ指定するかどうかを選択します。この設定を有効にすることをお勧めします。
+
会話開始機能を有効にすると、デフォルトで「自動モード」が選択されます。「手動モード」は、ナレッジベースにデータソースを追加した後にのみ有効にできます。link:manage-knowledgebase.html["ナレッジベースの設定を変更する方法について説明します。"]です。

.. * FSx for ONTAPファイルシステム*：新しいナレッジベースを定義すると、Workload Factoryは新しいAmazon FSx for NetApp ONTAPボリュームを作成して保存します。新しいボリュームを作成する既存のファイルシステム名とSVM（Storage VM）を選択します。
.. * Snapshotポリシー*：Workload Factoryストレージインベントリで定義されている既存のポリシーのリストからSnapshotポリシーを選択します。ナレッジベースの定期的なスナップショットは、選択したスナップショットポリシーに基づいて頻度で自動的に作成されます。
+
必要なSnapshotポリシーが存在しない場合は https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["Snapshot ポリシーを作成します"]、ボリュームを含むStorage VM上で実行できます。



. [ナレッジベースの作成]*を選択して、ナレッジベースをGenAIに追加します。
+
ナレッジベースの作成中は、進行状況インジケータが表示されます。

+
ナレッジベースを作成したら、新しいナレッジベースにデータソースを追加するか、データソースを追加せずにプロセスを終了するかを選択できます。[データソースの追加]*を選択し、ここで1つ以上のデータソースを追加することをお勧めします。





== ナレッジベースへのデータソースの追加

1つまたは複数のデータソースを追加して、組織のデータをナレッジベースに入力できます。

.タスクの内容
サポートされるデータソースの最大数は10です。

.手順
. [データソースの追加]*を選択すると、*[ファイルシステムの選択]*ページが表示されます。
. *ファイルシステムを選択*：データソースファイルが存在するFSx for ONTAPファイルシステムを選択し、* Next *を選択します。
. *ボリュームを選択*：データソースファイルが格納されているボリュームを選択し、*[次へ]*を選択します。
+
SMBプロトコルを使用して保存されているファイルを選択する場合は、ドメイン、IPアドレス、ユーザ名、パスワードなどのActive Directory情報を入力する必要があります。

. *データソースを選択*：ファイルを保存した場所に基づいてデータソースの場所を選択します。これは、ボリューム全体、またはボリューム内の特定のフォルダまたはサブフォルダにすることができ、* Next *を選択します。
. * AIパラメーターの定義*：*チャンク戦略*セクションで、データソースがナレッジベースと統合されている場合に、生成AIエンジンがデータソースコンテンツをチャンクに分割する方法を定義します。次のいずれかの方法を選択できます。
+
** *Multi-sentence chunking*:データソースの情報をセンテンス定義のチャンクに編成します。各チャンクを構成する文の数を選択できます(最大100 )。
** *オーバーラップベースのチャンク*:データソースからの情報を文字定義のチャンクに編成し、隣接するチャンクとオーバーラップすることができます。各チャンクのサイズを文字単位で選択し、各チャンクが隣接するチャンクとどの程度重なるかを選択できます。チャンクサイズは50～3000文字、オーバーラップパーセンテージは1～99%の範囲で設定できます。
+

NOTE: オーバーラップ率を高く設定すると、取得精度がわずかに向上するだけで、ストレージ要件が大幅に増加します。



. 権限対応*セクション（SMBプロトコルを使用するボリューム上に選択したデータソースがある場合にのみ表示）で、選択を有効または無効にできます。
+
** *有効*:このナレッジベースにアクセスするチャットボットのユーザーは、アクセス権を持つデータソースからのクエリに対する応答のみを取得します。
** *無効*:チャットボットのユーザーは、統合されたすべてのデータソースからコンテンツを使用して応答を受信します。


. [追加]*を選択して、このデータソースをナレッジベースに追加します。


.結果
データソースがナレッジベースに埋め込まれ始めます。データソースが完全に埋め込まれると、ステータスが「埋め込み」から「埋め込み」に変わります。

単一のデータソースをナレッジベースに追加したら、チャットボットシミュレータウィンドウでローカルにテストし、必要な変更を加えてから、ユーザーがチャットボットを使用できるようにします。同じ手順に従って、ナレッジベースにデータソースを追加することもできます。
