---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, genai' 
summary: ワークロードファクトリーのAIワークロード機能の最新情報をご確認ください。 
---
= 生成AI向けBlueXP  ワークロードファクトリの最新情報
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ワークロードファクトリのジェネレーティブAIワークロード機能の最新情報をご確認ください。



== 2025年6月29日



=== 汎用 NFS/SMB ファイルシステムでホストされるデータソースのサポート

汎用SMBまたはNFS共有からデータソースを追加できるようになりました。これにより、Amazon FSx for NetApp ONTAP以外のファイルシステムでホストされているボリュームに保存されているファイルも含めることができます。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["ナレッジベースにデータソースを追加する"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["コネクタにデータソースを追加する"]



== 2025年6月3日



=== 運用の監視と追跡に使用可能なトラッカー

GenAIでTracker監視機能が利用可能になりました。Trackerを使用すると、保留中、進行中、完了済みの操作の進行状況とステータスを監視および追跡したり、操作タスクとサブタスクの詳細を確認したり、問題や失敗を診断したり、失敗した操作のパラメータを編集したり、失敗した操作を再試行したりできます。

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["BlueXP ワークロード ファクトリーの Tracker を使用してワークロード操作を監視する"]



=== 知識ベースの再ランク付けモデルを選択する

ナレッジベースで使用する特定のリランカーモデルを選択することで、再ランク付けされたクエリ結果の関連性を高めることができます。GenAIは、Cohere RerankモデルとAmazon Rerankモデルをサポートしています。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



== 2025年5月4日



=== Amazon Q Business 向け NetApp コネクタのサポート

GenAI のこのリリースでは、NetApp Connector for Amazon Q Business のサポートが導入され、Amazon Q Business 用のコネクタを作成できるようになりました。Amazon Bedrock用の 生成AIナレッジベースを構築するよりも、初期設定が少なくて済み、Amazon Q Business AIアシスタントをすばやく簡単に活用できます。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Amazon Q Business 用の NetApp コネクタを作成する"]



=== 強化されたチャットモデルサポート

生成AIでは、ナレッジベース用に次の追加チャットモデルがサポートされるようになりました。

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AIモデル"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titanテキストモデル"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llamaモデル"^]
* link:https://docs.ai21.com/["Jamba 1.5モデル"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohereコマンドモデル"^]
* link:https://aws.amazon.com/bedrock/deepseek/["ディープシークモデル"^]


生成AIは、Amazon Bedrockがサポートする各プロバイダのモデルをサポートしています。link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Bedrockでサポートされる基盤モデル"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



=== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。== 2025年3月2日



=== 組み込みチャットボットの機能強化

質問と回答をクリップボードに直接コピーしたり、チャットウィンドウのサイズを調整したり、タイトルを変更したりできるようになりました。さらに、チャット応答にテーブルを含めることができるようになりました。テーブルはコピー可能です。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["生成AIナレッジベースのテスト"]



=== チャット応答引用のサポート

チャットの応答に、応答を生成するために使用されたファイルとデータのチャンクをリストする引用が含まれるようになりました。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["生成AIナレッジベースのテスト"]



=== ファイル形式のサポートの強化

このリリースの 生成AIでは、ファイルサポートが強化されています。

* チャットモデル機能CSVサポートが改善されました。これにより、CSVファイルからデータを照会するときに、より便利な応答が可能になります。
* 生成AIは、データソースからApache Parquetファイルを取り込むことができるようになりました。
* 生成AIでは、画像を含むMicrosoft Word DOCXファイルの取り込みがサポートされるようになりました。DOCXドキュメント内に埋め込まれた画像がスキャンされ、埋め込まれた画像からのテキストインサイトがナレッジベースのクエリへの応答に含まれます。


link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["サポートされるデータソースファイル形式"]



== 2025年2月2日



=== Amazon Nova基盤モデルのサポート

生成AIはAmazon Nova基盤モデルをサポートするようになりました。Amazon Nova Micro、Amazon Nova Lite、およびAmazon Nova Proがサポートされています。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/requirements-knowledge-base.html["GenAIの要件"]



=== データソースのファイルタイプフィルタリング

生成AIでは、データソースを追加するときに、データソーススキャンに含める特定のファイルタイプの選択がサポートされるようになりました。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["ナレッジベースへのデータソースの追加"]



=== データソースのファイル変更日のフィルタリング

生成AIでは、データソースの追加時に変更日によってデータソーススキャンに含めるファイルのフィルタリングがサポートされるようになりました。インクルードされるファイルの変更日の範囲を選択できます。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["ナレッジベースへのデータソースの追加"]



=== 画像ファイルのサポートとPDFファイルのサポートの強化

生成AIでは、画像やグラフの説明、ドキュメントテキストからのインサイトを使用してナレッジベースのクエリへの応答を強化できるようになり、より豊かで高品質な回答が得られるようになりました。生成AIでは、PDFファイル内の画像ファイルおよび画像をスキャンできるようになりました（マルチモーダルファイルサポートとも呼ばれます）。画像またはPDFファイルのスキャンを選択した場合は、画像のテキスト（PDFドキュメントに埋め込まれた画像を含む）がデータソースにスキャンされ、スキャンからのインサイトがナレッジベースのクエリへの応答に含まれます。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["ナレッジベースへのデータソースの追加"]



=== ハイブリッド検索と再検索のサポート

生成AIでは、ハイブリッド検索を使用して結果をリランク付けすることで、検索結果の関連性と精度を大幅に向上させることができます。ハイブリッド検索は、従来のキーワードベース検索の強みと高度な高密度ベクトルベースのセマンティック検索技術を組み合わせたものです。標準的なキーワード検索結果は、近い一致と言語的なニュアンスで強化され、関連性が向上します。その後、生成AIはCohere RerankやAmazon Rerankなどの高度なリランキングモデルを使用してこれらの結果をさらに絞り込み、最も関連性の高い結果を返します。この機能は、新しく作成されたナレッジベースで使用できます。

link:https://docs.netapp.com/us-en/workload-genai/general/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["生成AI向けBlueXP  ワークロードファクトリの詳細"]



== 2025年1月5日



=== カスタムSnapshot名

アドホックスナップショットのスナップショット名を指定できるようになりました。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["スナップショットでナレッジベースを保護"]



=== カスタムAIエンジンインスタンス名

導入時にAIエンジンインスタンスにカスタム名を付けることができるようになりました。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/deploy-infrastructure.html["GenAIインフラの導入"]



=== 破損または欠落している 生成AIインフラの再構築

AIエンジンインスタンスが破損したり、何らかの理由で削除されたりした場合は、ワークロードファクトリに再構築を依頼できます。ワークロードファクトリは、再構築が完了した後、ナレッジベースをインフラストラクチャに自動的に再接続して、すぐに使用できるようにします。

link:https://docs.netapp.com/us-en/workload-genai/general/troubleshooting.html["トラブルシューティング"]



== 2024年12月1日



=== Snapshotからナレッジベースをクローニング

生成AI向けのBlueXP  ワークロードファクトリでは、スナップショットからのナレッジベースのクローニングがサポートされるようになりました。これにより、ナレッジベースの迅速なリカバリと既存のデータソースを使用した新しいナレッジベースの作成が可能になり、データのリカバリと開発に役立ちます。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#clone-a-knowledge-base["ナレッジベースの複製"]



=== オンプレミスのONTAPクラスタの検出とレプリケーション

オンプレミスのONTAPクラスタデータを検出してFSx for ONTAPファイルシステムにレプリケートすることで、AIのナレッジベースを強化できます。オンプレミスの検出とレプリケーションのすべてのワークフローは、ストレージインベントリの新しい*オンプレミスONTAP *タブから実行できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["オンプレミスの ONTAP クラスタを検出"]



== 2024年11月3日



=== 個人識別情報をデータガードレールでマスクする

ジェネレーティブAIワークロードには、BlueXP  分類を基盤とするデータガードレール機能が導入されています。データガードレール機能は、個人識別情報(PII)を識別してマスクし、組織の機密データのコンプライアンスを維持し、セキュリティを強化するのに役立ちます。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXPの分類について説明します"^]



== 2024年9月29日



=== ナレッジベースボリュームのSnapshotとリストアのサポート

ナレッジベースのポイントインタイムコピーを作成することで、ジェネレーティブAIワークロードのデータを保護できるようになりました。これにより、偶発的な損失からデータを保護したり、ナレッジベースの設定の変更をテストしたりできます。以前のバージョンのナレッジベースボリュームはいつでもリストアできます。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["ナレッジベースボリュームのスナップショットの作成"]

https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["ナレッジベースボリュームのスナップショットのリストア"]



=== スケジュール済みスキャンを一時停止

スケジュールされたデータソーススキャンを一時停止できるようになりました。デフォルトでは、ジェネレーティブAIワークロードは各データソースを毎日スキャンし、各ナレッジベースに新しいデータを取り込みます。最新の変更を取り込みたくない場合（テスト中やスナップショットのリストア中など）は、スケジュールされたスキャンを一時停止していつでも再開できます。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/manage-knowledgebase.html["ナレッジベースの管理"]



=== ナレッジベースでのデータ保護ボリュームのサポート

ナレッジベースボリュームを選択する際に、NetApp SnapMirrorレプリケーション関係の一部であるデータ保護ボリュームを選択できるようになりました。これにより、SnapMirrorレプリケーションですでに保護されているボリュームにナレッジベースを格納できます。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html["ナレッジベースに統合するデータソースを特定する"]



== 2024年9月1日



=== その他のチャンキング戦略

ジェネレーティブAIワークロードで、データソースに対してマルチセンテンスチャンキングとオーバーラップベースのチャンキングがサポートされるようになりました。



=== ナレッジベースごとの専用ボリューム

ジェネレーティブAIワークロードでは、新しいナレッジベースごとに専用のAmazon FSx for NetApp ONTAPボリュームが作成されるようになりました。これにより、ナレッジベースごとに個別のSnapshotポリシーが有効になり、障害やデータポイズニングに対する保護が強化されます。



== 2024 年 8 月 4 日



=== Amazon CloudWatch Logsの統合

ジェネレーティブAIワークロードがAmazon CloudWatch Logsと統合され、ジェネレーティブAIワークロードのログファイルを監視できるようになりました。



=== チャットボットアプリケーションの例

NetAppワークロードファクトリ 生成AIサンプルアプリケーションを使用すると、Webベースのチャットボットアプリケーションで直接対話することで、公開されたNetAppワークロードファクトリナレッジベースからの認証と取得をテストできます。



== 2024年7月7日



=== 生成AI向けワークロードファクトリの初回リリース

最初のリリースには、組織のデータを埋め込むことによってカスタマイズされたナレッジベースを開発する機能が含まれています。ナレッジベースには、ユーザー用のチャットボットアプリケーションからアクセスできます。この機能により、組織固有の質問に対する正確で適切な回答が保証され、すべてのユーザーの満足度と生産性が向上します。
