---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Workload FactoryのAIワークロード機能の最新情報をご確認ください。 
---
= 新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload FactoryのGenerative AI Workloads機能の最新情報をご確認ください。



== 2024年9月1日



=== その他のチャンキング戦略

ジェネレーティブAIワークロードで、データソースに対してマルチセンテンスチャンキングとオーバーラップベースのチャンキングがサポートされるようになりました。



=== ナレッジベースごとの専用ボリューム

ジェネレーティブAIワークロードでは、新しいナレッジベースごとに専用のAmazon FSx for NetApp ONTAPボリュームが作成されるようになりました。これにより、ナレッジベースごとに個別のSnapshotポリシーが有効になり、障害やデータポイズニングに対する保護が強化されます。



== 2024 年 8 月 4 日



=== Amazon CloudWatch Logsの統合

ジェネレーティブAIワークロードがAmazon CloudWatch Logsと統合され、ジェネレーティブAIワークロードのログファイルを監視できるようになりました。



=== チャットボットアプリケーションの例

NetAppワークロードファクトリ 生成AIサンプルアプリケーションを使用すると、Webベースのチャットボットアプリケーションで直接対話することで、公開されたNetAppワークロードファクトリナレッジベースからの認証と取得をテストできます。



== 2024年7月7日



=== GenAI向けWorkload Factoryの初版リリース

最初のリリースには、組織のデータを埋め込むことによってカスタマイズされたナレッジベースを開発する機能が含まれています。ナレッジベースには、ユーザー用のチャットボットアプリケーションからアクセスできます。この機能により、組織固有の質問に対する正確で適切な回答が保証され、すべてのユーザーの満足度と生産性が向上します。
