---
sidebar: sidebar 
permalink: general/monitor-operations.html 
keywords: monitor genai, monitor jobs, track jobs, tracker 
summary: NetApp Workload Factory for GenAI の Tracker を使用して、ワークロード操作を追跡し、ジョブの進行状況を監視します。 
---
= NetApp Workload FactoryのTrackerでワークロード操作を監視する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Workload Factory の Tracker を使用して、ワークロード操作の実行を監視および追跡し、タスクの進行状況を監視します。

.タスクの内容
NetApp Workload Factory には監視機能の Tracker が用意されており、ワークロード操作の進行状況とステータスを監視および追跡したり、操作タスクとサブタスクの詳細を確認したり、問題や障害を診断したりできます。

Trackerでは、いくつかのアクションを使用できます。期間（過去24時間、7日、14日、または30日）、ワークロード、ステータス、およびユーザでジョブをフィルタリングしたり、検索機能を使用してジョブを検索したり、ジョブテーブルをCSVファイルとしてダウンロードしたりできます。Trackerはいつでも更新でき、失敗した処理をすばやく再試行したり、失敗した処理のパラメータを編集して処理を再試行したりできます。

トラッカーは、操作に応じて2つのレベルの監視をサポートします。ファイルシステムの導入などの各タスクには、タスクの説明、ステータス、開始時間、タスク期間、ユーザー、地域、プロキシリソース、タスクID、および関連するすべてのサブタスクが表示されます。API応答を表示して、処理中に発生した問題を把握することができます。

Trackerタスクレベルと例::
+
--
* レベル1（タスク）：ファイルシステムの展開を追跡します。
* レベル2（サブタスク）：ファイルシステムの展開に関連するサブタスクを追跡します。


--
処理のステータス:: Trackerの動作ステータスは、_進行中_、_成功_、_失敗_です。
+
--
動作周波数:: 処理の頻度は、ジョブタイプとジョブスケジュールに基づいて決まります。


--
イヘントホシ:: イベントはユーザインターフェイスに30日間保持されます。




== 運用の追跡と監視

Tracker を使用して、Workload Factory コンソールで操作を追跡および監視します。

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. ワークロード メニューから、*管理* を選択し、次に *トラッカー* を選択します。
. Tracker では、フィルターまたは検索を使用してジョブの結果を絞り込みます。求人レポートをダウンロードすることもできます。




== View APIヨウキユウ

TrackerのタスクのコードボックスでAPIリクエストを表示します。

.手順
. トラッカーでタスクを選択します。
. アクション メニューを選択し、*API リクエストの表示*を選択します。




== 失敗した処理を再試行する

Trackerで失敗した操作を再試行します。失敗した処理のエラーメッセージをコピーすることもできます。


NOTE: 失敗した処理は10回まで再試行できます。

.手順
. トラッカーで、失敗した操作を選択します。
. アクション メニューを選択し、[再試行] を選択します。


.結果
処理が再開されます。



== 失敗した処理を編集して再試行してください

失敗した操作のパラメータを編集し、Trackerの外部で操作を再試行してください。

.手順
. トラッカーで、失敗した操作を選択します。
. アクション メニューを選択し、*編集して再試行*を選択します。
+
処理ページにリダイレクトされ、パラメータを編集して処理を再試行できます。



.結果
処理が再開されます。[Tracker]に移動して処理のステータスを確認します。
