---
sidebar: sidebar 
permalink: knowledge-base/example-chatbot-application.html 
keywords: ai, example, sample, chatbot, app, application, local 
summary: サンプル チャットボット アプリケーションをインストールして実行し、ナレッジ ベースをテストし、Workload Factory API を使用して独自の生成 AI アプリケーションを作成する方法を学習できます。 
---
= 生成AI外部サンプルチャットボットアプリケーションを使用する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ナレッジ ベースを設定、アクティブ化、公開すると、外部のアプリケーション開発者は、 NetAppが提供するオープン ソースのサンプル チャットボット アプリケーションを設定および実行して、ナレッジ ベースを操作し、Workload Factory API を使用して独自の生成 AI アプリケーションを作成する方法を学習できるようになります。

.手順
. link:create-knowledgebase.html["ナレッジベースの作成"]です。
. link:activate-authentication.html["認証をアクティブ化"] をクリックします。
+
これにより、ナレッジベースでAPI要求を認証できるようになり、APIエンドポイントを使用する際にトークンの検証とACLが必要になります。

+

NOTE: このナレッジベースと統合する外部チャットアプリケーションは、ナレッジベースの認証設定で設定したものと同じ認証プロバイダ(発行者)を使用する必要があります。

. link:publish-knowledgebase.html["ナレッジベースの公開"] 外部アプリケーションのAPIアクセスを有効にします。
+
ナレッジベースが公開されると、APIエンドポイントに外部からアクセスできるようになり、ナレッジベースを外部チャットアプリケーション（例のチャットボットアプリケーションなど）と統合できます。

. からサンプルのチャットボットアプリケーションパッケージをダウンロードし https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample["GitHub"^]ます。
. パッケージに含まれているREADMEファイルの指示に従って、チャットボットアプリケーションをインストールして実行します。
. を参照し http://localhost:9091["http://localhost:9091"] てアプリケーションにログインします。
+
チャットボットアプリケーションの例が表示されます。





== 詳細

https://console.workloads.netapp.com/api-doc["ワークロードファクトリー API ドキュメント"]
