---
sidebar: sidebar 
permalink: connector/identify-data-sources-connector.html 
keywords: data sources, chatbot, documents, knowledge base, connector 
summary: ナレッジベースに統合するFSx for ONTAPファイルシステムにあるドキュメント（データソース）を特定または作成します。これらのデータソースを使用すると、組織に関連するデータに基づいて、ナレッジベースでユーザクエリに対する正確でパーソナライズされた回答を提供できます。 
---
= コネクタに追加するデータソースを特定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コネクタに統合するFSx for ONTAPファイルシステムに存在するドキュメント（データソース）を特定または作成します。これらのデータソースを使用すると、Amazon Q Businessは、組織に関連するデータに基づいて、ユーザークエリに対して正確でパーソナライズされた回答を提供できます。



== データソースの最大数

サポートされるデータソースの最大数は10です。



== データソースの場所

データソースは、単一のボリュームに格納することも、ボリューム内のフォルダに格納することも、Amazon FSx for NetApp ONTAPファイルシステム上のSMB共有やNFSエクスポートに格納することもできます。また、NetApp SnapMirrorデータ保護関係にあるAmazon FSx for NetApp ONTAPボリュームにデータソースを保存することもできます。

ボリュームまたはフォルダ内の個 々 のドキュメントを選択することはできません。したがって、データソースを含む各ボリュームまたはフォルダに、ナレッジベースと統合すべきではない無関係なドキュメントが含まれていないことを確認する必要があります。

各コネクタには複数のデータソースを追加できますが、すべてのデータソースをAWSアカウントからアクセスできるFSx for ONTAPファイルシステムに配置する必要があります。

各データソースの最大ファイルサイズは50MBです。



== サポートされるプロトコル

コネクタは、NFSまたはSMB / CIFSプロトコルを使用するボリュームのデータをサポートします。SMBプロトコルを使用して保存されているファイルを選択する場合は、コネクタがこれらのボリューム上のファイルにアクセスできるように、Active Directory情報を入力する必要があります。これには、Active Directoryドメイン、IPアドレス、ユーザ名、パスワードが含まれます。

SMB経由でアクセスされる共有（ファイルまたはディレクトリ）にデータソースを格納する場合、その共有にアクセスする権限を持つチャットボットのユーザまたはグループのみがデータにアクセスできます。この「権限認識機能」が有効になっている場合、AIシステムはAuth0内のユーザのEメールを、SMB共有上のファイルの表示または使用を許可されているユーザと比較します。チャットボットは、埋め込まれたファイルのユーザー権限に基づいて回答を提供します。

たとえば、コネクタに10個のファイル(データソース)を統合し、そのうちの2個が制限された情報を含む人事ファイルである場合、これら2つのファイルへのアクセスを認証されたチャットボットユーザーのみが、それらのファイルからのデータを含むチャットボットから応答を受け取ります。


NOTE: Amazon Q Business Connectorにデータソースを追加する場合、データソースファイルにはユーザー権限のみが適用されます。グループ権限は適用されません。


NOTE: データソース内のファイルにテキストがない場合(テキストのない画像など)、Amazon Q Businessはインデックスを作成しませんが、テキストがないことを示すエントリをAmazon CloudWatch Logsに記録します。



== サポートされるデータソースファイル形式

現在、NetApp ONTAP Connector for Amazon Qでサポートされているデータソースのファイル形式は次のとおりです。

[cols="2*"]
|===
| ファイル形式 | エクステンション 


| カンマ区切り値ファイル | .csv 


| JSONとJSONP | .json 


| マークダウン | .md 


| Microsoft Word | .docx 


| プレーンテキスト | .txt 


| ポータブルドキュメントフォーマット | .pdf 


| Microsoft PowerPoint | .pptまたは.pptx 


| ハイパーテキストマークアップ言語 | .html からのアクセスが可能です 


| 拡張マークアップ言語 | .xml に保存されます 


| XSLT | .XSLT 


| Microsoft Excel | .xls 


| リッチテキスト形式 | .rtf 
|===